"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { OUR_STORY_TRANSLATIONS } from "@/data/translations/ourStory";
import { WHY_US_TRANSLATIONS } from "@/data/translations/whyUs";
import { FAQS_TRANSLATIONS } from "@/data/translations/faqs";
import { CONTACT_TRANSLATIONS } from "@/data/translations/contact";

export const LANGUAGES = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
];

const TRANSLATIONS = {
  // ── ENGLISH (Default) ──
  en: {
    // Header & Ticker
    ticker_f2c: "Farmer to Consumer",
    ticker_nobrokers: "No Brokers",
    ticker_panindia: "PAN India Delivery",
    ticker_support: "Support:",
    ticker_help: "Help Centre",
    nav_shop: "Shop Nectars",
    nav_story: "Our Story",
    nav_whyus: "Why Bee Desi",
    nav_nmr: "NMR Lab Purity",
    nav_faqs: "FAQs & Terroirs",
    nav_contact: "Contact & HQ",
    nav_quiz: "Find Your Nectar",
    nav_cart: "Cart",
    nav_search_placeholder: "Search raw honey by floral source: Jamun, Acacia, Mangrove, Sidr...",
    nav_search_btn: "Search",

    // Home Hero
    hero_tag: "Single-Origin Nectars · 100% Raw Forest Harvest",
    hero_h1_part1: "India's Purest",
    hero_h1_part2: "Raw Honey.",
    hero_subtext: "Single-flora. Truly unheated. Free from imported sugar syrups and factory pasteurization. Independently fingerprinted by German Bruker 400MHz NMR spectroscopy to guarantee 0.00% synthetic adulterants.",
    hero_social_trust: "Over 4,500+ jars delivered across India · Zero Syrup Adulteration",
    hero_btn_shop: "Shop Single-Origin Nectars",
    hero_btn_story: "Our Story",
    hero_btn_quiz: "Terroir Sommelier Quiz",
    hero_metric1_val: "0.00%",
    hero_metric1_lbl: "Sugar Syrup Adulteration",
    hero_metric2_val: "< 35°C",
    hero_metric2_lbl: "Cold-Extracted & Unheated",
    hero_metric3_val: "400MHz",
    hero_metric3_lbl: "Bruker NMR Certified",
    hero_badge_title: "Bruker 400MHz NMR Certified:",
    hero_badge_sub: "0.00% Sugar Syrup Detected",

    // Why Us Strip
    strip_title1: "Bruker NMR Certified",
    strip_desc1: "German 400MHz NMR spectroscopy confirms 0.00% synthetic sugar adulteration per batch.",
    strip_title2: "Direct Forager Payouts",
    strip_desc2: "No brokers or middlemen. Paying ₹320–₹380/kg directly to indigenous forest gatherers.",
    strip_title3: "Raw & Unheated (<35°C)",
    strip_desc3: "Never boiled or pasteurized. Living diastase and invertase enzymes remain 100% active.",
    strip_title4: "Single-Flora Purity",
    strip_desc4: "Single origin, single floral season. Never blended from unknown commercial syrups.",
    strip_footer_tag: "ETHICAL APICULTURE · 100% TRANSPARENT BATCH FINGERPRINTS",
    strip_footer_link: "Read our 6 purity differentiators",

    // Catalog Section
    cat_tag: "The Seasonal Flora Portfolio",
    cat_h2: "Single-Flora Forest Canopies",
    cat_sub: "Each jar captures the unadulterated nectar of a single botanical bloom in a single Indian forest terroir. Never blended with sugar syrup, never micro-filtered.",
    cat_quiz_box_title: "Not sure which nectar to choose?",
    cat_quiz_box_link: "Take 30-sec Terroir Matcher Quiz →",
    cat_search_placeholder: "Search flora, terroir, tasting notes...",
    cat_showing: "Showing",
    cat_harvests: "single-flora harvests",
    cat_sort: "Sort:",
    cat_sort_featured: "Featured First",
    cat_sort_rating: "Highest Rated",
    cat_sort_low: "Price: Low to High",
    cat_sort_high: "Price: High to Low",
    cat_terroirs: "Terroirs:",
    cat_all_regions: "All Regions",
    cat_intentions: "Health Intention:",
    cat_all_intentions: "All Intentions",
    cat_add_btn: "Add to Basket",
    cat_added: "Added",
    cat_direct_harvest: "Direct Harvest",
    cat_explore: "Explore Harvest",

    // Footer
    footer_tag: "Farmer to Consumer · No Brokers · PAN India",
    footer_h2_1: "From India's Ancient Forests",
    footer_h2_2: "to Your Table",
    footer_p: "Raw, unheated, NMR-certified honey. Sourced with reverence from tribal communities who've tended these forests for generations.",
    footer_btn: "Explore Our Honeys",
    footer_nmr: "NMR Certified",
    footer_delivery: "Free Delivery",
    footer_cold: "Cold-Chain",
    footer_secure: "Secure Checkout",
    footer_brand_desc: "India's purest single-origin raw honeys. Est. 1996. Tested by German Bruker 400MHz NMR.",
  },

  // ── HINDI (हिन्दी) ──
  hi: {
    ticker_f2c: "किसान से सीधे उपभोक्ता तक",
    ticker_nobrokers: "बिना किसी दलाल के",
    ticker_panindia: "पूरे भारत में डिलीवरी",
    ticker_support: "सहायता:",
    ticker_help: "सहायता केंद्र",
    nav_shop: "शहद खरीदें",
    nav_story: "हमारी कहानी",
    nav_whyus: "बी देसी क्यों?",
    nav_nmr: "एनएमआर लैब शुद्धता",
    nav_faqs: "अक्सर पूछे जाने वाले सवाल",
    nav_contact: "संपर्क व मुख्यालय",
    nav_quiz: "अपना शहद चुनें",
    nav_cart: "टोकरी",
    nav_search_placeholder: "जामुन, बबूल, मैंग्रोव, बेरी शहद खोजें...",
    nav_search_btn: "खोजें",

    hero_tag: "एकल पुष्प अमृत · 100% शुद्ध वन शहद",
    hero_h1_part1: "भारत का सबसे शुद्ध",
    hero_h1_part2: "कच्चा शहद।",
    hero_subtext: "एकल पुष्प। पूरी तरह से बिना गर्म किया हुआ। चीनी सिरप और पेस्ट्यूराइजेशन से पूरी तरह मुक्त। जर्मन ब्रूकर 400MHz एनएमआर स्पेक्ट्रोस्कोपी द्वारा 0.00% मिलावट रहित प्रमाणित।",
    hero_social_trust: "भारत भर में 4,500+ से अधिक जार डिलीवर · 0% चीनी सिरप",
    hero_btn_shop: "शुद्ध शहद देखें",
    hero_btn_story: "हमारी कहानी पढ़ें",
    hero_btn_quiz: "शहद चयन क्विज",
    hero_metric1_val: "0.00%",
    hero_metric1_lbl: "चीनी सिरप मिलावट (शून्य)",
    hero_metric2_val: "< 35°C",
    hero_metric2_lbl: "कच्चा व बिना गर्म किया हुआ",
    hero_metric3_val: "400MHz",
    hero_metric3_lbl: "जर्मन ब्रूकर एनएमआर प्रमाणित",
    hero_badge_title: "ब्रूकर 400MHz एनएमआर प्रमाणित:",
    hero_badge_sub: "0.00% चीनी सिरप मिलावट की पुष्टि",

    strip_title1: "ब्रूकर एनएमआर लैब प्रमाणित",
    strip_desc1: "जर्मनी की 400MHz एनएमआर स्पेक्ट्रोस्कोपी हर बैच में 0.00% मिलावट की पुष्टि करती है।",
    strip_title2: "आदिवासियों को सीधा उचित मूल्य",
    strip_desc2: "बिना बिचौलियों के, वनवासियों को सीधे ₹320-₹380 प्रति किलो का भुगतान।",
    strip_title3: "कच्चा व बिना गर्म किया (<35°C)",
    strip_desc3: "कभी उबाला नहीं जाता। डायस्टेस व इनवर्टेज एंजाइम 100% जीवित रहते हैं।",
    strip_title4: "एकल पुष्प शुद्धता",
    strip_desc4: "एक मौसम, एक फूल का अमृत। अनजान सिरप से कभी नहीं मिलाया जाता।",
    strip_footer_tag: "प्राकृतिक मधुमक्खी पालन · 100% पारदर्शी बैच रिपोर्ट",
    strip_footer_link: "हमारी 6 शुद्धता विशेषताएं पढ़ें",

    cat_tag: "प्राकृतिक मौसमी शहद संग्रह",
    cat_h2: "भारतीय वनों का एकल पुष्प अमृत",
    cat_sub: "प्रत्येक जार एक विशिष्ट भारतीय जंगल के एक विशेष फूल के अमृत से भरा है। इसमें कभी चीनी नहीं मिलाई जाती।",
    cat_quiz_box_title: "शहद चुनने में मदद चाहिए?",
    cat_quiz_box_link: "30-सेकंड का शहद क्विज लें →",
    cat_search_placeholder: "फूल, क्षेत्र या स्वाद अनुसार खोजें...",
    cat_showing: "कुल",
    cat_harvests: "एकल-पुष्प शहद उपलब्ध",
    cat_sort: "क्रमबद्ध करें:",
    cat_sort_featured: "विशेष",
    cat_sort_rating: "उच्चतम रेटिंग",
    cat_sort_low: "कीमत: कम से अधिक",
    cat_sort_high: "कीमत: अधिक से कम",
    cat_terroirs: "क्षेत्र:",
    cat_all_regions: "सभी क्षेत्र",
    cat_intentions: "स्वास्थ्य लाभ:",
    cat_all_intentions: "सभी लाभ",
    cat_add_btn: "टोकरी में डालें",
    cat_added: "जोड़ दिया गया",
    cat_direct_harvest: "सीधी फसल",
    cat_explore: "विस्तार से देखें",

    footer_tag: "किसान से सीधे आप तक · बिना दलाल · पूरे भारत में",
    footer_h2_1: "भारत के प्राचीन वनों से",
    footer_h2_2: "आपकी थाली तक",
    footer_p: "कच्चा, बिना गर्म किया हुआ, एनएमआर-प्रमाणित शहद। पीढ़ियों से जंगलों की रक्षा करने वाले आदिवासियों से सीधे प्राप्त।",
    footer_btn: "सभी शहद देखें",
    footer_nmr: "एनएमआर प्रमाणित",
    footer_delivery: "मुफ्त डिलीवरी",
    footer_cold: "कोल्ड-चेन सुरक्षा",
    footer_secure: "सुरक्षित भुगतान",
    footer_brand_desc: "भारत का सबसे शुद्ध एकल-पुष्प कच्चा शहद। स्थापना 1996। जर्मन ब्रूकर एनएमआर द्वारा परीक्षित।",
  },

  // ── PUNJABI (ਪੰਜਾਬੀ) ──
  pa: {
    ticker_f2c: "ਕਿਸਾਨ ਤੋਂ ਸਿੱਧਾ ਗਾਹਕ ਤੱਕ",
    ticker_nobrokers: "ਬਿਨਾਂ ਕਿਸੇ ਵਿਚੋਲੇ ਦੇ",
    ticker_panindia: "ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ ਡਿਲੀਵਰੀ",
    ticker_support: "ਸਹਾਇਤਾ:",
    ticker_help: "ਸਹਾਇਤਾ ਕੇਂਦਰ",
    nav_shop: "ਸ਼ਹਿਦ ਖਰੀਦੋ",
    nav_story: "ਸਾਡੀ ਕਹਾਣੀ",
    nav_whyus: "ਬੀ ਦੇਸੀ ਕਿਉਂ?",
    nav_nmr: "ਐਨਐਮਆਰ ਸ਼ੁੱਧਤਾ",
    nav_faqs: "ਸਵਾਲ-ਜਵਾਬ",
    nav_contact: "ਸੰਪਰਕ",
    nav_quiz: "ਆਪਣਾ ਸ਼ਹਿਦ ਚੁਣੋ",
    nav_cart: "ਟੋਕਰੀ",
    nav_search_placeholder: "ਜਾਮਣ, ਕਿੱਕਰ, ਬੇਰੀ ਸ਼ਹਿਦ ਲੱਭੋ...",
    nav_search_btn: "ਖੋਜੋ",

    hero_tag: "ਇੱਕੋ ਫੁੱਲ ਦਾ ਅੰਮ੍ਰਿਤ · 100% ਕੱਚਾ ਜੰਗਲੀ ਸ਼ਹਿਦ",
    hero_h1_part1: "ਭਾਰਤ ਦਾ ਸਭ ਤੋਂ ਸ਼ੁੱਧ",
    hero_h1_part2: "ਕੱਚਾ ਸ਼ਹਿਦ।",
    hero_subtext: "ਇੱਕੋ ਫੁੱਲ ਤੋਂ ਤਿਆਰ। ਪੂਰੀ ਤਰ੍ਹਾਂ ਬਿਨਾਂ ਗਰਮ ਕੀਤਾ। ਚੀਨੀ ਦੇ ਸ਼ਰਬਤ ਤੋਂ ਮੁਕਤ। ਜਰਮਨ ਬਰੂਕਰ 400MHz ਐਨਐਮਆਰ ਦੁਆਰਾ 0.00% ਮਿਲਾਵਟ ਰਹਿਤ ਪ੍ਰਮਾਣਿਤ।",
    hero_social_trust: "ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ 4,500+ ਤੋਂ ਵੱਧ ਜਾਰ ਡਿਲੀਵਰ · 0% ਸ਼ੱਕਰ ਮਿਲਾਵਟ",
    hero_btn_shop: "ਸ਼ੁੱਧ ਸ਼ਹਿਦ ਦੇਖੋ",
    hero_btn_story: "ਸਾਡੀ ਕਹਾਣੀ ਪੜ੍ਹੋ",
    hero_btn_quiz: "ਸ਼ਹਿਦ ਚੋਣ ਕੁਇਜ਼",
    hero_metric1_val: "0.00%",
    hero_metric1_lbl: "ਸ਼ੂਗਰ ਸਿਰਪ ਮਿਲਾਵਟ",
    hero_metric2_val: "< 35°C",
    hero_metric2_lbl: "ਕੱਚਾ ਤੇ ਅਨਹੀਟਿਡ",
    hero_metric3_val: "400MHz",
    hero_metric3_lbl: "ਜਰਮਨ ਐਨਐਮਆਰ ਟੈਸਟਡ",
    hero_badge_title: "ਬਰੂਕਰ 400MHz ਐਨਐਮਆਰ ਪ੍ਰਮਾਣਿਤ:",
    hero_badge_sub: "0.00% ਖੰਡ ਸ਼ਰਬਤ ਦੀ ਪੁਸ਼ਟੀ",

    strip_title1: "ਬਰੂਕਰ ਐਨਐਮਆਰ ਟੈਸਟਡ",
    strip_desc1: "ਜਰਮਨੀ ਵਿੱਚ ਟੈਸਟ ਕੀਤਾ, ਹਰ ਬੈਚ ਵਿੱਚ 0.00% ਮਿਲਾਵਟ ਦੀ ਪੁਸ਼ਟੀ।",
    strip_title2: "ਕਿਸਾਨਾਂ ਨੂੰ ਸਿੱਧੀ ਅਦਾਇਗੀ",
    strip_desc2: "ਬਿਨਾਂ ਵਿਚੋਲਿਆਂ ਦੇ, ਜੰਗਲ ਵਾਸੀਆਂ ਨੂੰ ₹320-₹380 ਪ੍ਰਤੀ ਕਿਲੋ ਸਿੱਧਾ ਭੁਗਤਾਨ।",
    strip_title3: "ਕੱਚਾ ਤੇ ਬਿਨਾਂ ਉਬਾਲਿਆ (<35°C)",
    strip_desc3: "ਕਦੇ ਵੀ ਉਬਾਲਿਆ ਨਹੀਂ ਜਾਂਦਾ। ਲਾਈਵ ਐਨਜ਼ਾਈਮ ਪੂਰੀ ਤਰ੍ਹਾਂ ਸਰਗਰਮ ਰਹਿੰਦੇ ਹਨ।",
    strip_title4: "ਸਿੰਗਲ-ਫਲੋਰਾ ਸ਼ੁੱਧਤਾ",
    strip_desc4: "ਇੱਕ ਸੀਜ਼ਨ, ਇੱਕ ਫੁੱਲ ਦਾ ਸ਼ਹਿਦ। ਬਾਜ਼ਾਰੀ ਸ਼ਰਬਤਾਂ ਵਿੱਚ ਨਹੀਂ ਰਲਾਇਆ ਜਾਂਦਾ।",
    strip_footer_tag: "ਨਿਰਪੱਖ ਸ਼ਹਿਦ ਪਾਲਣ · 100% ਪਾਰਦਰਸ਼ੀ ਲੈਬ ਰਿਪੋਰਟਾਂ",
    strip_footer_link: "ਸਾਡੇ 6 ਮੁੱਖ ਨਿਯਮ ਪੜ੍ਹੋ",

    cat_tag: "ਮੌਸਮੀ ਸ਼ਹਿਦ ਸੰਗ੍ਰਹਿ",
    cat_h2: "ਭਾਰਤੀ ਜੰਗਲਾਂ ਦਾ ਸ਼ੁੱਧ ਅੰਮ੍ਰਿਤ",
    cat_sub: "ਹਰ ਜਾਰ ਵਿੱਚ ਇੱਕ ਖਾਸ ਫੁੱਲ ਦਾ ਕੁਦਰਤੀ ਸ਼ਹਿਦ ਹੈ। ਇਸ ਵਿੱਚ ਕਦੇ ਵੀ ਚੀਨੀ ਜਾਂ ਸ਼ਰਬਤ ਨਹੀਂ ਮਿਲਾਇਆ ਜਾਂਦਾ।",
    cat_quiz_box_title: "ਸ਼ਹਿਦ ਚੁਣਨ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?",
    cat_quiz_box_link: "30-ਸਕਿੰਟ ਦਾ ਕੁਇਜ਼ ਲਓ →",
    cat_search_placeholder: "ਫੁੱਲ ਜਾਂ ਖੇਤਰ ਮੁਤਾਬਕ ਖੋਜੋ...",
    cat_showing: "ਕੁੱਲ",
    cat_harvests: "ਸ਼ਹਿਦ ਉਪਲਬਧ",
    cat_sort: "ਤਰਤੀਬ:",
    cat_sort_featured: "ਖਾਸ",
    cat_sort_rating: "ਸਭ ਤੋਂ ਵੱਧ ਰੇਟਿੰਗ",
    cat_sort_low: "ਕੀਮਤ: ਘੱਟ ਤੋਂ ਵੱਧ",
    cat_sort_high: "ਕੀਮਤ: ਵੱਧ ਤੋਂ ਘੱਟ",
    cat_terroirs: "ਖੇਤਰ:",
    cat_all_regions: "ਸਾਰੇ ਖੇਤਰ",
    cat_intentions: "ਸਿਹਤ ਲਾਭ:",
    cat_all_intentions: "ਸਾਰੇ ਲਾਭ",
    cat_add_btn: "ਟੋਕਰੀ ਵਿੱਚ ਪਾਓ",
    cat_added: "ਜੋੜਿਆ ਗਿਆ",
    cat_direct_harvest: "ਸਿੱਧੀ ਫਸਲ",
    cat_explore: "ਵੇਰਵਾ ਦੇਖੋ",

    footer_tag: "ਕਿਸਾਨ ਤੋਂ ਸਿੱਧਾ ਤੁਹਾਡੇ ਤੱਕ · ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ",
    footer_h2_1: "ਭਾਰਤ ਦੇ ਪ੍ਰਾਚੀਨ ਜੰਗਲਾਂ ਤੋਂ",
    footer_h2_2: "ਤੁਹਾਡੇ ਘਰ ਤੱਕ",
    footer_p: "ਕੱਚਾ, ਬਿਨਾਂ ਗਰਮ ਕੀਤਾ, ਐਨਐਮਆਰ ਪ੍ਰਮਾਣਿਤ ਸ਼ਹਿਦ। ਪੀੜ੍ਹੀਆਂ ਤੋਂ ਜੰਗਲਾਂ ਦੀ ਦੇਖਭਾਲ ਕਰਨ ਵਾਲਿਆਂ ਤੋਂ ਪ੍ਰਾਪਤ।",
    footer_btn: "ਸਾਰੇ ਸ਼ਹਿਦ ਦੇਖੋ",
    footer_nmr: "ਐਨਐਮਆਰ ਪ੍ਰਮਾਣਿਤ",
    footer_delivery: "ਮੁਫਤ ਡਿਲੀਵਰੀ",
    footer_cold: "ਕੋਲਡ-ਚੇਨ ਸੁਰੱਖਿਅਤ",
    footer_secure: "ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ",
    footer_brand_desc: "ਭਾਰਤ ਦਾ ਸਭ ਤੋਂ ਸ਼ੁੱਧ ਕੱਚਾ ਸ਼ਹਿਦ। ਸਥਾਪਿਤ 1996। ਜਰਮਨ ਬਰੂਕਰ ਐਨਐਮਆਰ ਪ੍ਰਮਾਣਿਤ।",
  },

  // ── GUJARATI (ગુજરાતી) ──
  gu: {
    ticker_f2c: "ખેડૂતથી સીધા ગ્રાહક સુધી",
    ticker_nobrokers: "દલાલો વિના",
    ticker_panindia: "સમગ્ર ભારતમાં ડિલિવરી",
    ticker_support: "સહાય:",
    ticker_help: "સહાય કેન્દ્ર",
    nav_shop: "મધ ખરીદો",
    nav_story: "અમારી વાર્તા",
    nav_whyus: "બી દેશી શા માટે?",
    nav_nmr: "એનએમઆર શુદ્ધતા",
    nav_faqs: "પ્રશ્નોત્તરી",
    nav_contact: "સંપર્ક",
    nav_quiz: "તમારું મધ શોધો",
    nav_cart: "ટોપલી",
    nav_search_placeholder: "જાંબુ, બાવળ, સિદ્ધ મધ શોધો...",
    nav_search_btn: "શોધો",

    hero_tag: "એકલ પુષ્પ અમૃત · 100% કાચું જંગલી મધ",
    hero_h1_part1: "ભારતનું સૌથી શુદ્ધ",
    hero_h1_part2: "કાચું મધ.",
    hero_subtext: "સિંગલ-ફ્લોરા. ગરમ કર્યા વિનાનું. ખાંડની ચાસણી અને પ્રોસેસિંગથી સંપૂર્ણ મુક્ત. જર્મન બ્રુકર 400MHz એનએમઆર દ્વારા 0.00% શુદ્ધતા પ્રમાણિત.",
    hero_social_trust: "ભારતભરમાં 4,500+ થી વધુ જાર પહોંચાડ્યા · 0% ખાંડ ભેળસેળ",
    hero_btn_shop: "શુદ્ધ મધ જુઓ",
    hero_btn_story: "અમારી વાર્તા વાંચો",
    hero_btn_quiz: "મધ પસંદગી ક્વિઝ",
    hero_metric1_val: "0.00%",
    hero_metric1_lbl: "ખાંડની ચાસણી ભેળસેળ (શૂન્ય)",
    hero_metric2_val: "< 35°C",
    hero_metric2_lbl: "કાચું અને અનહીટેડ",
    hero_metric3_val: "400MHz",
    hero_metric3_lbl: "જર્મન એનએમઆર પ્રમાણિત",
    hero_badge_title: "બ્રુકર 400MHz એનએમઆર પ્રમાણિત:",
    hero_badge_sub: "0.00% ખાંડની ચાસણીની પુષ્ટિ",

    strip_title1: "બ્રુકર એનએમઆર પ્રમાણિત",
    strip_desc1: "જર્મનીમાં ટેસ્ટ થયેલું, દરેક બેચમાં 0.00% ભેળસેળની ખાતરી.",
    strip_title2: "આદિવાસીઓને સીધો વેતન",
    strip_desc2: "કોઈ વચેટિયા વિના, જંગલમાંથી મધ એકઠું કરનારાઓને સીધા ₹320-₹380 પ્રતિ કિલો.",
    strip_title3: "કાચું અને ઉકાળ્યા વિના (<35°C)",
    strip_desc3: "ક્યારેય ગરમ કરાતું નથી. બધા જીવંત ઉત્સેચકો સક્રિય રહે છે.",
    strip_title4: "સિંગલ-ફ્લોરા શુદ્ધતા",
    strip_desc4: "એક ઋતુ, એક ફૂલનું અમૃત. ક્યારેય સસ્તી ચાસણીમાં ભેળવાતું નથી.",
    strip_footer_tag: "પ્રાકૃતિક મધપાલન · 100% પારદર્શક લેબ અહેવાલો",
    strip_footer_link: "અમારા 6 શુદ્ધતાના નિયમો વાંચો",

    cat_tag: "કુદરતી મોસમી મધ સંગ્રહ",
    cat_h2: "ભારતીય વનોનું અમૃત",
    cat_sub: "દરેક બરણીમાં ચોક્કસ જંગલના એક જ ફૂલનું મધ છે. તેમાં ક્યારેય ખાંડ ભેળવવામાં આવતી નથી.",
    cat_quiz_box_title: "મધ પસંદ કરવામાં મદદ જોઈએ છે?",
    cat_quiz_box_link: "30-સેકન્ડની ક્વિઝ લો →",
    cat_search_placeholder: "ફૂલ અથવા પ્રદેશ અનુસાર શોધો...",
    cat_showing: "કુલ",
    cat_harvests: "મધ ઉપલબ્ધ",
    cat_sort: "ક્રમ:",
    cat_sort_featured: "ખાસ",
    cat_sort_rating: "ટોચનું રેટિંગ",
    cat_sort_low: "કિંમત: ઓછી થી વધુ",
    cat_sort_high: "કિંમત: વધુ થી ઓછી",
    cat_terroirs: "વિસ્તાર:",
    cat_all_regions: "બધા વિસ્તારો",
    cat_intentions: "સ્વાસ્થ્ય લાભ:",
    cat_all_intentions: "બધા લાભો",
    cat_add_btn: "ટોપલીમાં ઉમેરો",
    cat_added: "ઉમેરાઈ ગયું",
    cat_direct_harvest: "સીધો પાક",
    cat_explore: "વિગત જુઓ",

    footer_tag: "ખેડૂતથી સીધા તમારા ઘર સુધી · સમગ્ર ભારતમાં",
    footer_h2_1: "ભારતના પ્રાચીન જંગલોમાંથી",
    footer_h2_2: "તમારી થાળી સુધી",
    footer_p: "કાચું, અશુદ્ધિ રહિત, એનએમઆર પ્રમાણિત મધ. પેઢીઓથી જંગલની રક્ષા કરતા આદિવાસીઓ પાસેથી સીધું મેળવેલું.",
    footer_btn: "બધા મધ જુઓ",
    footer_nmr: "એનએમઆਰ પ્રમાણિત",
    footer_delivery: "મફત ડિલિવરી",
    footer_cold: "કોલ્ડ-ચેન સુરક્ષિત",
    footer_secure: "સુરક્ષિત ચુકવણી",
    footer_brand_desc: "ભારતનું સૌથી શુદ્ધ કાચું મધ. સ્થાપના 1996. જર્મન બ્રુકર એનએમઆર પ્રમાણિત.",
  },

  // ── MARATHI (मराठी) ──
  mr: {
    ticker_f2c: "शेतकऱ्यांकडून थेट ग्राहकांपर्यंत",
    ticker_nobrokers: "दलालांशिवाय",
    ticker_panindia: "संपूर्ण भारतात डिलिव्हरी",
    ticker_support: "मदत:",
    ticker_help: "मदत केंद्र",
    nav_shop: "मध खरेदी करा",
    nav_story: "आमची गोष्ट",
    nav_whyus: "बी देसी का?",
    nav_nmr: "एनएमआर लॅब शुद्धता",
    nav_faqs: "वारंवार विचारले जाणारे प्रश्न",
    nav_contact: "संपर्क आणि मुख्यालय",
    nav_quiz: "आपला मध निवडा",
    nav_cart: "बास्केट",
    nav_search_placeholder: "जांभूळ, खैर, बाभूळ मध शोधा...",
    nav_search_btn: "शोधा",

    hero_tag: "एकल पुष्प अमृत · 100% शुद्ध वन मध",
    hero_h1_part1: "भारतातील सर्वात शुद्ध",
    hero_h1_part2: "कच्चा मध.",
    hero_subtext: "एकल पुष्प. पूर्णपणे गरम न केलेला. साखर सिरप आणि फॅक्टरी पाश्चरायझेशनपासून पूर्णपणे मुक्त. जर्मन ब्रुकर 400MHz एनएमआर स्पेक्ट्रोस्कोपीद्वारे 0.00% भेसळमुक्त प्रमाणित.",
    hero_social_trust: "संपूर्ण भारतात 4,500+ पेक्षा जास्त जार वितरित · 0% साखर भेसळ",
    hero_btn_shop: "शुद्ध मध पहा",
    hero_btn_story: "आमची गोष्ट वाचा",
    hero_btn_quiz: "मध निवड चाचणी",
    hero_metric1_val: "0.00%",
    hero_metric1_lbl: "साखर सिरप भेसळ (शून्य)",
    hero_metric2_val: "< 35°C",
    hero_metric2_lbl: "कच्चा व गरम न केलेला",
    hero_metric3_val: "400MHz",
    hero_metric3_lbl: "जर्मन एनएमआर प्रमाणित",
    hero_badge_title: "ब्रुकर 400MHz एनएमआर प्रमाणित:",
    hero_badge_sub: "0.00% साखर सिरप भेसळमुक्त",

    strip_title1: "ब्रुकर एनएमआर प्रमाणित",
    strip_desc1: "जर्मनीमध्ये चाचणी, प्रत्येक बॅचमध्ये 0.00% भेसळमुक्ततेची हमी.",
    strip_title2: "आदिवासींना थेट मोबदला",
    strip_desc2: "दलालांशिवाय, जंगलातील मध गोळा करणाऱ्यांना थेट ₹320-₹380 प्रति किलो मोबदला.",
    strip_title3: "कच्चा व न उकळलेला (<35°C)",
    strip_desc3: "कधीही उकळला जात नाही. सर्व सजीव एन्झाईम्स 100% सक्रिय राहतात.",
    strip_title4: "सिंगल-फ्लोरा शुद्धता",
    strip_desc4: "एका हंगामातील एका फुलाचे अमृत. स्वस्त सिरपमध्ये कधीही मिसळले जात नाही.",
    strip_footer_tag: "नैसर्गिक मधमाशी पालन · 100% पारदर्शक लॅब अहवाल",
    strip_footer_link: "आमचे 6 शुद्धता नियम वाचा",

    cat_tag: "हंगामी मध संकलन",
    cat_h2: "भारतीय वनांचे शुद्ध अमृत",
    cat_sub: "प्रत्येक जारमध्ये विशिष्ट जंगलातील एकाच फुलाचा मध आहे. यात कधीही साखर मिसळली जात नाही.",
    cat_quiz_box_title: "मध निवडण्यात मदत हवी आहे?",
    cat_quiz_box_link: "30-सेकंदांची क्विझ सोडवा →",
    cat_search_placeholder: "फुल किंवा प्रदेशानुसार शोधा...",
    cat_showing: "एकूण",
    cat_harvests: "मध उपलब्ध",
    cat_sort: "क्रमवारी:",
    cat_sort_featured: "विशेष",
    cat_sort_rating: "सर्वोच्च रेटिंग",
    cat_sort_low: "किंमत: कमी ते जास्त",
    cat_sort_high: "किंमत: जास्त ते कमी",
    cat_terroirs: "प्रदेश:",
    cat_all_regions: "सर्व प्रदेश",
    cat_intentions: "आरोग्य फायदे:",
    cat_all_intentions: "सर्व फायदे",
    cat_add_btn: "बास्केटमध्ये टाका",
    cat_added: "टाकले गेले",
    cat_direct_harvest: "थेट पीक",
    cat_explore: "तपशील पहा",

    footer_tag: "शेतकऱ्यांकडून थेट तुमच्या घरापर्यंत · संपूर्ण भारतात",
    footer_h2_1: "भारताच्या प्राचीन जंगलांतून",
    footer_h2_2: "आपल्या ताटापर्यंत",
    footer_p: "कच्चा, प्रक्रिया न केलेला, एनएमआर प्रमाणित मध. पिढ्यानपिढ्या जंगलांचे रक्षण करणाऱ्या आदिवासींकडून थेट प्राप्त.",
    footer_btn: "सर्व मध पहा",
    footer_nmr: "एनएमआर प्रमाणित",
    footer_delivery: "मोफत डिलिव्हरी",
    footer_cold: "कोल्ड-चेन सुरक्षित",
    footer_secure: "सुरक्षित पेमेंट",
    footer_brand_desc: "भारतातील सर्वात शुद्ध कच्चा मध. स्थापना 1996. जर्मन ब्रुकर एनएमआर प्रमाणित.",
  },

  // ── BENGALI (বাংলা) ──
  bn: {
    ticker_f2c: "কৃষক থেকে সরাসরি গ্রাহক পর্যন্ত",
    ticker_nobrokers: "দালাল ছাড়া",
    ticker_panindia: "সমগ্র ভারতে ডেলিভারি",
    ticker_support: "সাহায্য:",
    ticker_help: "সাহায্য কেন্দ্র",
    nav_shop: "মধু কিনুন",
    nav_story: "আমাদের গল্প",
    nav_whyus: "কেন বি দেশী?",
    nav_nmr: "এনএমআর ল্যাব বিশুদ্ধতা",
    nav_faqs: "সাধারণ জিজ্ঞাসা",
    nav_contact: "যোগাযোগ",
    nav_quiz: "মধু বাছুন",
    nav_cart: "ঝুড়ি",
    nav_search_placeholder: "জাম, বাবলা, সুন্দরবনের মধু খুঁজুন...",
    nav_search_btn: "খুঁজুন",

    hero_tag: "একক ফুলের নির্যাস · 100% খাঁটি বন মধু",
    hero_h1_part1: "ভারতের সবচেয়ে খাঁটি",
    hero_h1_part2: "কাঁচা মধু।",
    hero_subtext: "একক ফুল থেকে সংগৃহীত। সম্পূর্ণভাবে গরম না করা। ভেজাল চিনির সিরাপ এবং পাস্তুরায়ন থেকে মুক্ত। জার্মান ব্রুকার 400MHz এনএমআর দ্বারা 0.00% বিশুদ্ধতা প্রমাণিত।",
    hero_social_trust: "ভারত জুড়ে 4,500+ এর বেশি জার ডেলিভারি · 0% চিনির ভেজাল",
    hero_btn_shop: "খাঁটি মধু দেখুন",
    hero_btn_story: "আমাদের গল্প পড়ুন",
    hero_btn_quiz: "মধু বাছাই কুইজ",
    hero_metric1_val: "0.00%",
    hero_metric1_lbl: "চিনির সিরাপের ভেজাল (শূন্য)",
    hero_metric2_val: "< 35°C",
    hero_metric2_lbl: "কাঁচা ও ফুটিয়ে না রাখা",
    hero_metric3_val: "400MHz",
    hero_metric3_lbl: "জার্মান এনএমআর পরীক্ষিত",
    hero_badge_title: "ব্রুকার 400MHz এনএমআর শংসাপত্র:",
    hero_badge_sub: "0.00% চিনির সিরাপের অনুপস্থিতি নিশ্চিত",

    strip_title1: "ব্রুকার এনএমআর পরীক্ষিত",
    strip_desc1: "জার্মানিতে পরীক্ষিত, প্রতিটি ব্যাচে 0.00% ভেজালের নিশ্চয়তা।",
    strip_title2: "মৌয়ালদের সরাসরি ন্যায্য মজুরি",
    strip_desc2: "কোন মধ্যস্বত্বভোগী ছাড়া, বনবাসীদের সরাসরি ₹320-₹380 প্রতি কেজি মূল্য।",
    strip_title3: "কাঁচা ও ফোটানো ছাড়া (<35°C)",
    strip_desc3: "কখনোই গরম করা হয় না। সমস্ত প্রাকৃতিক এনজাইম সক্রিয় থাকে।",
    strip_title4: "একক-ফুল বিশুদ্ধতা",
    strip_desc4: "এক ঋতু, এক ফুলের মধু। সস্তা সিরাপে মেশানো হয় না।",
    strip_footer_tag: "প্রাকৃতিক মৌমাছি পালন · 100% স্বচ্ছ ল্যাব রিপোর্ট",
    strip_footer_link: "আমাদের ৬টি বিশুদ্ধতার নীতি পড়ুন",

    cat_tag: "মৌসুমি মধু সংগ্রহ",
    cat_h2: "ভারতীয় বনের একক ফুলের মধু",
    cat_sub: "প্রতিটি পাত্রে একটি নির্দিষ্ট বনের একটি নির্দিষ্ট ফুলের খাঁটি মধু রয়েছে। এতে কখনো চিনি মেশানো হয় না।",
    cat_quiz_box_title: "মধু বেছে নিতে সাহায্য চান?",
    cat_quiz_box_link: "৩০-সেকেন্ডের কুইজ নিন →",
    cat_search_placeholder: "ফুল বা অঞ্চল অনুযায়ী খুঁজুন...",
    cat_showing: "মোট",
    cat_harvests: "মধু উপলব্ধ",
    cat_sort: "সাজান:",
    cat_sort_featured: "বিশেষ",
    cat_sort_rating: "সর্বোচ্চ রেটিং",
    cat_sort_low: "দাম: কম থেকে বেশি",
    cat_sort_high: "দাম: বেশি থেকে কম",
    cat_terroirs: "অঞ্চল:",
    cat_all_regions: "সব অঞ্চল",
    cat_intentions: "স্বাস্থ্য উপকারিতা:",
    cat_all_intentions: "সব উপকারিতা",
    cat_add_btn: "ঝুড়িতে যোগ করুন",
    cat_added: "যোগ করা হয়েছে",
    cat_direct_harvest: "সরাসরি ফসল",
    cat_explore: "বিস্তারিত দেখুন",

    footer_tag: "কৃষক থেকে সরাসরি আপনার বাড়ি · সমগ্র ভারতে",
    footer_h2_1: "ভারতের প্রাচীন বন থেকে",
    footer_h2_2: "আপনার খাবারের টেবিলে",
    footer_p: "কাঁচা, অপরিশোধিত, এনএমআর পরীক্ষিত মধু। বন সংরক্ষণকারী আদিবাসীদের থেকে সরাসরি সংগৃহীত।",
    footer_btn: "সব মধু দেখুন",
    footer_nmr: "এনএমআর পরীক্ষিত",
    footer_delivery: "বিনামূল্যে ডেলিভারি",
    footer_cold: "কোল্ড-চেন সুরক্ষিত",
    footer_secure: "নিরাপদ পেমেন্ট",
    footer_brand_desc: "ভারতের সবচেয়ে খাঁটি কাঁচা মধু। স্থাপিত ১৯৯৬। জার্মান ব্রুকার এনএমআর পরীক্ষিত।",
  },

  // ── TAMIL (தமிழ்) ──
  ta: {
    ticker_f2c: "விவசாயியிடமிருந்து நேரடியாக",
    ticker_nobrokers: "இடைத்தரகர்கள் இல்லை",
    ticker_panindia: "இந்தியா முழுவதும் விநியோகம்",
    ticker_support: "உதவி:",
    ticker_help: "உதவி மையம்",
    nav_shop: "தேன் வாங்க",
    nav_story: "எங்கள் கதை",
    nav_whyus: "ஏன் பீ தேசி?",
    nav_nmr: "என்.எம்.ஆர் ஆய்வக தூய்மை",
    nav_faqs: "கேள்வி பதில்கள்",
    nav_contact: "தொடர்பு",
    nav_quiz: "தேனைத் தேர்வு செய்ய",
    nav_cart: "கூடை",
    nav_search_placeholder: "நாவல், கருவேலம், காட்டுத் தேன்...",
    nav_search_btn: "தேடு",

    hero_tag: "ஒற்றை மலர் தேன் · 100% இயற்கை காட்டுத் தேன்",
    hero_h1_part1: "இந்தியாவின் மிகத் தூய்மையான",
    hero_h1_part2: "இயற்கை தேன்.",
    hero_subtext: "சூடுபடுத்தப்படாத இயற்கை தேன். சர்க்கரை பாகு சேர்க்கப்படாதது. ஜெர்மன் புரூக்கர் 400MHz என்.எம்.ஆர் பரிசோதனை மூலம் 0.00% கலப்படமற்றது என நிரூபிக்கப்பட்டது.",
    hero_social_trust: "இந்தியா முழுவதும் 4,500+ ஜாடிகள் வழங்கப்பட்டன · 0% சர்க்கரை கலப்படம்",
    hero_btn_shop: "சுத்தமான தேன் பார்க்க",
    hero_btn_story: "எங்கள் கதை வாசிக்க",
    hero_btn_quiz: "தேன் தேர்வு வினாடி வினா",
    hero_metric1_val: "0.00%",
    hero_metric1_lbl: "சர்க்கரை பாகு கலப்படம் (பூஜ்ஜியம்)",
    hero_metric2_val: "< 35°C",
    hero_metric2_lbl: "சூடுபடுத்தப்படாத இயற்கை தேன்",
    hero_metric3_val: "400MHz",
    hero_metric3_lbl: "ஜெர்மன் என்.எம்.ஆர் சான்றளிக்கப்பட்டது",
    hero_badge_title: "புரூக்கர் 400MHz என்.எம்.ஆர் சான்றிதழ்:",
    hero_badge_sub: "0.00% சர்க்கரை பாகு இல்லை என உறுதி",

    strip_title1: "என்.எம்.ஆர் பரிசோதிக்கப்பட்டது",
    strip_desc1: "ஜெர்மனியில் பரிசோதிக்கப்பட்டு, ஒவ்வொரு தொகுப்பிலும் 0.00% கலப்படமற்றது.",
    strip_title2: "பழங்குடியினருக்கு நேரடி ஊதியம்",
    strip_desc2: "இடைத்தரகர்கள் இன்றி, காட்டு மக்களுக்கு நேரடியாக ₹320-₹380 ஊதியம்.",
    strip_title3: "இயற்கையானது (<35°C)",
    strip_desc3: "சூடுபடுத்தப்படுவதில்லை. அனைத்து என்சைம்களும் உயிருடன் இருக்கும்.",
    strip_title4: "ஒற்றை மலர் தூய்மை",
    strip_desc4: "ஒரு பருவத்தின் ஒரு மலர் தேன். எந்த செயற்கை பாகுகளும் கலக்கப்படுவதில்லை.",
    strip_footer_tag: "இயற்கை தேனீ வளர்ப்பு · 100% வெளிப்படையான ஆய்வக அறிக்கை",
    strip_footer_link: "எங்கள் 6 தூய்மை விதிகளைப் படியுங்கள்",

    cat_tag: "பருவகால தேன் தொகுப்பு",
    cat_h2: "இந்திய காடுகளின் அற்புதம்",
    cat_sub: "ஒவ்வொரு ஜாடியிலும் குறிப்பிட்ட காட்டு மலரின் தூய தேன் உள்ளது. இதில் சர்க்கரை கலக்கப்படுவதில்லை.",
    cat_quiz_box_title: "தேன் தேர்வு செய்ய உதவி தேவையா?",
    cat_quiz_box_link: "30-விநாடி வினாடி வினா எடுக்கவும் →",
    cat_search_placeholder: "மலர் அல்லது பகுதி வாரியாக தேடவும்...",
    cat_showing: "மொத்தம்",
    cat_harvests: "தேன் வகைகள் உள்ளன",
    cat_sort: "வரிசைப்படுத்து:",
    cat_sort_featured: "சிறப்பானது",
    cat_sort_rating: "உயர் மதிப்பீடு",
    cat_sort_low: "விலை: குறைவிலிருந்து அதிகம்",
    cat_sort_high: "விலை: அதிகத்திலிருந்து குறைவு",
    cat_terroirs: "பகுதிகள்:",
    cat_all_regions: "அனைத்து பகுதிகள்",
    cat_intentions: "நன்மைகள்:",
    cat_all_intentions: "அனைத்து நன்மைகள்",
    cat_add_btn: "கூடையில் சேர்க்க",
    cat_added: "சேர்க்கப்பட்டது",
    cat_direct_harvest: "நேரடி அறுவடை",
    cat_explore: "விவரம் பார்க்க",

    footer_tag: "விவசாயியிடமிருந்து உங்கள் இல்லத்திற்கு · இந்தியா முழுவதும்",
    footer_h2_1: "இந்தியாவின் பழங்கால காடுகளிலிருந்து",
    footer_h2_2: "உங்கள் இல்லத்திற்கு",
    footer_p: "இயற்கையான, சூடுபடுத்தப்படாத என்.எம்.ஆர் பரிசோதிக்கப்பட்ட தேன். காடுகளை பாதுகாக்கும் பழங்குடி மக்களிடமிருந்து நேரடியாக.",
    footer_btn: "அனைத்து தேனையும் பார்க்க",
    footer_nmr: "என்.எம்.ஆர் சான்றளிக்கப்பட்டது",
    footer_delivery: "இலவச டெலிவரி",
    footer_cold: "பாதுகாப்பான விநியோகம்",
    footer_secure: "பாதுகாப்பான கட்டணம்",
    footer_brand_desc: "இந்தியாவின் மிகத் தூய்மையான இயற்கை தேன். நிறுவப்பட்டது 1996. ஜெர்மன் என்.எம்.ஆர் சான்றளிக்கப்பட்டது.",
  },

  // ── TELUGU (తెలుగు) ──
  te: {
    ticker_f2c: "రైతు నుండి నేరుగా వినియోగదారునికి",
    ticker_nobrokers: "మధ్యవర్తులు లేరు",
    ticker_panindia: "భారతదేశం అంతటా డెలివరీ",
    ticker_support: "సహాయం:",
    ticker_help: "సహాయ కేంద్రం",
    nav_shop: "తేనె కొనండి",
    nav_story: "మా కథ",
    nav_whyus: "బీ దేశీ ఎందుకు?",
    nav_nmr: "ఎన్.ఎం.ఆర్ ల్యాబ్ స్వచ్ఛత",
    nav_faqs: "తరచుగా అడిగే ప్రశ్నలు",
    nav_contact: "సంప్రదించండి",
    nav_quiz: "తేనె ఎంచుకోండి",
    nav_cart: "బుట్ట",
    nav_search_placeholder: "నేరేడు, తుమ్మ, అడవి తేనె...",
    nav_search_btn: "శోధించండి",

    hero_tag: "ఒకే పువ్వు తేనె · 100% సహజ అటవీ తేనె",
    hero_h1_part1: "భారతదేశంలో అత్యంత స్వచ్ఛమైన",
    hero_h1_part2: "పచ్చి తేనె.",
    hero_subtext: "వేడి చేయని స్వచ్ఛమైన తేనె. చక్కెర పాకం కలపబడలేదు. జర్మన్ బ్రూకర్ 400MHz ఎన్.ఎం.ఆర్ పరీక్ష ద్వారా 0.00% కల్తీ లేనిదిగా ధృవీకరించబడింది.",
    hero_social_trust: "భారతదేశం అంతటా 4,500+ కంటే ఎక్కువ జార్ల డెలివరీ · 0% చక్కెర కల్తీ",
    hero_btn_shop: "స్వచ్ఛమైన తేనె చూడండి",
    hero_btn_story: "మా కథ చదవండి",
    hero_btn_quiz: "తేనె ఎంపిక క్విజ్",
    hero_metric1_val: "0.00%",
    hero_metric1_lbl: "చక్కెర పాకం కల్తీ (సున్నా)",
    hero_metric2_val: "< 35°C",
    hero_metric2_lbl: "వేడి చేయని పచ్చి తేనె",
    hero_metric3_val: "400MHz",
    hero_metric3_lbl: "జర్మన్ ఎన్.ఎం.ఆర్ సర్టిఫైడ్",
    hero_badge_title: "బ్రూకర్ 400MHz ఎన్.ఎం.ఆర్ సర్టిఫైడ్:",
    hero_badge_sub: "0.00% చక్కెర పాకం లేదని నిర్ధారణ",

    strip_title1: "ఎన్.ఎం.ఆర్ పరీక్షించబడింది",
    strip_desc1: "జర్మనీలో పరీక్షించబడింది, ప్రతి బ్యాచ్‌లో 0.00% కల్తీ లేని హామీ.",
    strip_title2: "ఆదివాసీలకు నేరుగా చెల్లింపు",
    strip_desc2: "మధ్యవర్తులు లేకుండా, అటవీ సేకర్తలకు నేరుగా ₹320-₹380 చెల్లింపు.",
    strip_title3: "సహజమైనది (<35°C)",
    strip_desc3: "ఎప్పుడూ వేడి చేయబడదు. అన్ని సహజ ఎంజైములు సజీవంగా ఉంటాయి.",
    strip_title4: "సింగిల్-ఫ్లోరా స్వచ్ఛత",
    strip_desc4: "ఒక సీజన్, ఒకే పువ్వు తేనె. ఎటువంటి కృత్రిమ పాకం కలపబడదు.",
    strip_footer_tag: "సహజ తేనెటీగల పెంపకం · 100% పారదర్శక ల్యాబ్ నివేదికలు",
    strip_footer_link: "మా 6 స్వచ్ఛత సూత్రాలు చదవండి",

    cat_tag: "కాలానుగుణ తేనె సేకరణ",
    cat_h2: "భారతీయ అడవుల అమృతం",
    cat_sub: "ప్రతి సీసాలో ఒక నిర్దిష్ట అడవిలోని ఒకే పువ్వు తేనె ఉంటుంది. ఇందులో ఎప్పుడూ చక్కెర కలపబడదు.",
    cat_quiz_box_title: "తేనె ఎంచుకోవడంలో సహాయం కావాలా?",
    cat_quiz_box_link: "30-సెకన్ల క్విజ్ తీసుకోండి →",
    cat_search_placeholder: "పువ్వు లేదా ప్రాంతం ప్రకారం వెతకండి...",
    cat_showing: "మొత్తం",
    cat_harvests: "తేనె రకాలు ఉన్నాయి",
    cat_sort: "క్రమబద్ధీకరించు:",
    cat_sort_featured: "ప్రత్యేకమైనవి",
    cat_sort_rating: "అత్యుత్తమ రేటింగ్",
    cat_sort_low: "ధర: తక్కువ నుండి ఎక్కువ",
    cat_sort_high: "ధర: ఎక్కువ నుండి తక్కువ",
    cat_terroirs: "ప్రాంతాలు:",
    cat_all_regions: "అన్ని ప్రాంతాలు",
    cat_intentions: "ఆరోగ్య ప్రయోజనాలు:",
    cat_all_intentions: "అన్ని ప్రయోజనాలు",
    cat_add_btn: "బుట్టలో వేయండి",
    cat_added: "చేర్చబడింది",
    cat_direct_harvest: "నేరుగా పంట",
    cat_explore: "వివరాలు చూడండి",

    footer_tag: "రైతు నుండి నేరుగా మీ ఇంటికి · భారతదేశం అంతటా",
    footer_h2_1: "భారతదేశపు ప్రాచీన అడవుల నుండి",
    footer_h2_2: "మీ డైనింగ్ టేబుల్ వరకు",
    footer_p: "సహజమైన, వేడి చేయని, ఎన్.ఎం.ఆర్ సర్టిఫైడ్ తేనె. తరతరాలుగా అడవులను కాపాడుతున్న ఆదివాసీల నుండి నేరుగా.",
    footer_btn: "అన్ని తేనె రకాలు చూడండి",
    footer_nmr: "ఎన్.ఎం.ఆర్ సర్టిఫైడ్",
    footer_delivery: "ఉచిత డెలివరీ",
    footer_cold: "కోల్డ్-చైన్ రక్షణ",
    footer_secure: "సురక్షిత చెల్లింపు",
    footer_brand_desc: "భారతదేశంలో అత్యంత స్వచ్ఛమైన తేనె. స్థాపన 1996. జర్మన్ బ్రూకర్ ఎన్.ఎం.ఆర్ సర్టిఫైడ్.",
  },
};

// Merge page translations across all languages
Object.keys(TRANSLATIONS).forEach((code) => {
  const story = OUR_STORY_TRANSLATIONS[code] || OUR_STORY_TRANSLATIONS.en || {};
  const whyUs = WHY_US_TRANSLATIONS[code] || WHY_US_TRANSLATIONS.en || {};
  const faqs = FAQS_TRANSLATIONS[code] || FAQS_TRANSLATIONS.en || {};
  const contact = CONTACT_TRANSLATIONS[code] || CONTACT_TRANSLATIONS.en || {};

  TRANSLATIONS[code] = {
    ...TRANSLATIONS[code],
    ...story,
    ...whyUs,
    ...faqs,
    ...contact,
  };
});

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState("en");

  useEffect(() => {
    const saved = localStorage.getItem("preferred_lang");
    if (saved && TRANSLATIONS[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const changeLanguage = (code) => {
    if (TRANSLATIONS[code]) {
      setLanguageState(code);
      localStorage.setItem("preferred_lang", code);
    }
  };

  const t = (key, fallback = "") => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (dict && dict[key] !== undefined) {
      return dict[key];
    }
    // Fallback to English
    if (TRANSLATIONS.en && TRANSLATIONS.en[key] !== undefined) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  };

  const getStoryData = () => OUR_STORY_TRANSLATIONS[language] || OUR_STORY_TRANSLATIONS.en;
  const getWhyUsData = () => WHY_US_TRANSLATIONS[language] || WHY_US_TRANSLATIONS.en;
  const getFaqsData = () => FAQS_TRANSLATIONS[language] || FAQS_TRANSLATIONS.en;
  const getContactData = () => CONTACT_TRANSLATIONS[language] || CONTACT_TRANSLATIONS.en;

  return (
    <LanguageContext.Provider
      value={{
        language,
        changeLanguage,
        t,
        languages: LANGUAGES,
        getStoryData,
        getWhyUsData,
        getFaqsData,
        getContactData,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    // Return safe default if outside provider
    return {
      language: "en",
      changeLanguage: () => {},
      t: (k, fb = "") => fb || k,
      languages: LANGUAGES,
      getStoryData: () => OUR_STORY_TRANSLATIONS.en,
      getWhyUsData: () => WHY_US_TRANSLATIONS.en,
      getFaqsData: () => FAQS_TRANSLATIONS.en,
      getContactData: () => CONTACT_TRANSLATIONS.en,
    };
  }
  return ctx;
}

